apiVersion: v1
kind: Service
metadata:
  name: node_app
  labels:
    app: node_app
spec:
  type: NodePort
  ports:
  - port: 3004
    targetPort: 3004
    nodePort: 30007
  selector:
    app: node_app

